
export const ON_NEXT_QUESTION_CLICKED = "ON_NEXT_QUESTION_CLICKED";
export const ON_PREVIOUS_QUESTION_CLICKED = "ON_PREVIOUS_QUESTION_CLICKED";
export const ON_LOAD_QUESTIONS = "ON_LOAD_QUESTIONS";
export const ON_LOAD_QUIZ_NAMES = "ON_LOAD_QUIZ_NAMES";
export const ON_ANSWER_CLICKED = "ON_ANSWER_CLICKED";